name: 'SemVer Bump Enviroment'
description: 'Automatically bumps and syncs semver version for applications that have multiple enviroments.'
author: 'Luís Duarte (LuisDuarte1)'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'git-merge'
  color: 'blue'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
