name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

  test-action:
    name: GitHub Actions E2E Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Action - Simple bump
        id: test-action1
        uses: ./
        with:
          current_environment: production
          production_version: "1.2.0"
          bump_type: patch
      - name: Print Output
        run: echo "${{ steps.test-action1.outputs.new_version }}"

      - name: Test Action - Staging older than production
        id: test-action2
        uses: ./
        with:
          current_environment: staging
          production_version: "1.2.0"
          staging_version: 1.2.0-beta.2
          bump_type: prerelease
      - name: Print Output
        run: echo "${{ steps.test-action2.outputs.new_version }}"
